variables:
    WWW_DIR:  /www/password/
    HUGOARGS: --cleanDestinationDir

build:
  type: build
  script:
    - hugo ${HUGOARGS}
    - minify -aro public/ public/
  artifacts:
    paths:
      - public

deploy-production:
  type: deploy
  script:
    - rsync -a public/ $WWW_DIR
  environment:
    name: production
    url:  https://password.slxh.nl
  only:
    - master

deploy-ipfs:
  type: deploy
  script:
    - ipfs add -r public/
  environment:
      name: ipfs
      url: https://ipfs.slxh.nl/ipns/password.slxh.nl
  only:
    - master
